
services:
  redis:
    image: "redis:alpine"
    networks:
      - test
    ports:
      - "6379:6379"

#  app:
#    build:
#      context: .
#    networks:
#      - test
#    ports:
#      - "8080:8080"
#    depends_on:
#      - redis
#    environment:
#      - SPRING_REDIS_HOST=redis
#      - SPRING_REDIS_PORT=6379

networks:
  test: